### ISSUE TITLE
Doesn't change master if new master node created, and old deleted

### ISSUE THREAD

**Issue by lil-cain** [rackspace-cookbooks/mysql-multi#44]
Hi,

Due to https://github.com/rackspace-cookbooks/mysql-multi/blob/master/recipes/_find_master.rb#L25, the master attribute doesn't appear to change if you delete one master from chef, and create another node with the role.

Is there a reason the mysql-multi::_find_master recipe checks if the attribute is set before performing the search?

**Comment by martinb3** [comment]
@lil-cain The master attribute check is to support chef-solo and things like checkmate and consul; it gives the user the ability to override the value directly instead of rely on search every time (chef-solo can't search, and things like checkmate and consul use service discovery and don't need search either).

I'm concerned with how safe it might be to have a slave discover a new master and start using it without any user intervention; @prometheanfire, @jujugrrr, @cybermerc  -- should we auto-discover a new master node in chef if the previous one is deleted, or require user intervention? Also, chef is only running every 30 minutes, so it could take up to an hour to notice the node removed and reconfigure.

**Comment by jujugrrr** [comment]
Generally speaking, I would be to scare to let Chef decide for me of a new Master. However I understand @lil-cain needs.

Maybe we just need to document well what would be the user intervention.

**Comment by martinb3** [comment]
@lil-cain, I've submitted a PR with some updates to the docs about this, to make it more clear. If that meets your needs, let us know and we'll close this. We could, alternately, split out the attributes between an override attribute and an automatically detected attribute, and always run the search... but it seems like we have some consensus that it might be more dangerous to do so. If you want to consult with support overall, and see if they agree or disagree, we can proceed accordingly (and make that change if support would like it as a group, otherwise leave it as-is).

**Comment by lil-cain** [comment]
This seems reasonable - I think we're misusing the mysql-master search in one case, which is why this caused an issue. Used properly (i.e. just for mysql slaves) having to manually change the attribute makes sense since it would require manual intervention to change the slave anyway.

**Comment by jujugrrr** [comment]
> which is why this caused an issue

It might worth listing those places if you know them, so if we rewrite/improve mysql-multi we will stop to do it
